Repository DocQProject/DocQ-Frontend, pull requests merged in 2025-08, with the labels that each got.

#11 style(DQ-49): Update element layout, font style, and overall view
  src/App.jsx
  src/components/ClinicPage.jsx
  src/components/MainPage.jsx
  src/components/MyPage.jsx
  src/components/ReviewPage.jsx
  src/components/SignInPage.jsx
  src/components/SignUpPage.jsx
Labels: style

#13 feat(DQ-37): Implement Reservation section in ClinicPage and edit ClinicPage's UI
  src/App.jsx
  src/components/ClinicPage.jsx
  src/components/MyPage.jsx
  src/components/ReviewPage.jsx
Labels: feat

#16 feat(DQ-51): Add backend integration and event handling
  src/App.jsx
  src/api.js
  src/components/MainPage.jsx
  src/components/SignInPage.jsx
  src/components/SignUpPage.jsx
Labels: feat, refactor, style

#17 feat(DQ-54): Add backend integration
  src/api.js
  src/components/MainPage.jsx
Labels: feat, refactor

#18 feat(DQ-55): Implement search fetching and pagination handling
  src/api.js
  src/components/ClinicSearchResultPage.jsx
  src/components/MainPage.jsx
  src/components/NavigationBar.jsx
  src/components/Pagenation.jsx
  src/components/SignInPage.jsx
Labels: feat, refactor

#19 feat(DQ-52): Implement MyPage component with Profile, Reservation, Clinic, DeleteAccount
  src/api.js
  src/components/MyPage.jsx
Labels: feat

#21 feat(DQ-57): Implement infinite scroll for reviews and add fetchClinicInfo API
  src/App.jsx
  src/api.js
  src/components/ClinicPage.jsx
  src/components/ClinicSearchResultPage.jsx
  src/components/SideBar.jsx
  src/components/common/Pagenation.jsx
  src/components/common/StarPoint.jsx
  src/main.jsx
Labels: feat, refactor

#24 feat(DQ-60): Implement board and reservation features
  package-lock.json
  package.json
  src/App.jsx
  src/api.js
  src/components/Board.jsx
  src/components/ClinicPage.jsx
  src/components/PostCreate.jsx
  src/components/PostDetail.jsx
  src/components/PostEdit.jsx
  src/components/PostForm.jsx
  src/components/ReviewPage.jsx
Labels: feat
